# MinIO credentials
[sources.filesystem.credentials]
aws_access_key_id       = "admin"
aws_secret_access_key   = "password"
endpoint_url            = "http://localhost:9002"
region_name             = "eu-central-1"

[destination.filesystem.credentials]
aws_access_key_id       = "admin"
aws_secret_access_key   = "password"
endpoint_url            = "http://localhost:9002"
region_name             = "eu-central-1"

# https://dlthub.com/docs/dlt-ecosystem/destinations/iceberg
[iceberg_catalog]
iceberg_catalog_name    = "olake_iceberg"
iceberg_catalog_type    = "sql"

[iceberg_catalog.iceberg_catalog_config]
type                    = "sql"
uri                     = "postgresql+psycopg2://pgsource:pgsource@localhost:5432/pgsource"
warehouse               = "s3://iceberg/"
"s3.access-key-id"        = "admin"
"s3.secret-access-key"    = "password"
"s3.endpoint"             = "http://localhost:9002"
"s3.region"               = "eu-central-1"
"s3.path-style-access"    = "true"