# OLake CDC: Postgres -> MinIO (Iceberg)

services:
   olake:
      image: olakego/source-postgres:v0.7.3
      container_name:  olake
      volumes:
         - ./olake/config:/mnt/config
      command: >
        sync
        --config /mnt/config/source.json
        --destination /mnt/config/destination.json
        --catalog /mnt/config/catalog.json
        --state /mnt/config/state.json
      depends_on:
        postgres-source:
          condition: service_healthy # wait source to be ready
      networks:
         - data-network
      restart: always # continuous CDC (clean and restart)

networks:
   data-network:
      external: true